[theme]
base="light"
primaryColor = "#2a2a2a"            # Soft dark gray
backgroundColor = "#fff3f8"         # Soft pastel pink
secondaryBackgroundColor = "#ffe0ec" # Lighter pastel pink
textColor = "#1f1f1f"               # Dark text for better contrast